import bpy
ng = bpy.data.node_groups.new("TMP", 'GeometryNodeTree')
node = ng.nodes.new("GeometryNodeMeshCube")
print("MeshCube inputs:", [i.name for i in node.inputs])
node2 = ng.nodes.new("GeometryNodeMeshLine")
print("MeshLine inputs:", [i.name for i in node2.inputs])
print("MeshLine outputs:", [o.name for o in node2.outputs])
node3 = ng.nodes.new("GeometryNodeMeshGrid")
print("MeshGrid inputs:", [i.name for i in node3.inputs])
print("MeshGrid outputs:", [o.name for o in node3.outputs])
node4 = ng.nodes.new("GeometryNodeMeshCylinder")
print("MeshCylinder inputs:", [i.name for i in node4.inputs])
node5 = ng.nodes.new("GeometryNodeMeshIcoSphere")
print("MeshIcoSphere inputs:", [i.name for i in node5.inputs])
